### ISSUE TITLE
Idea for a realistic flow

### ISSUE THREAD

**Issue by saranvdev** [CodingEric/Erics-MagicaVoxel-Shaders#1]
Simple one:
Water should be removed after movement to a new position

Example 2d:

```
x0x
xxx
xxx
```

=

```
xxx
x0x
xxx
```

while by using flow we would have 2 water blocks by now.

**Comment by tyanyuy3125** [comment]
Got it. Wait for the next release.
(Though it's a little bit difficult to realise with the iterator of the MagicaVoxel, maybe the voxel color should be given and the flow will not be selective.)
Thank you.
