### ISSUE TITLE
Why the shader named ''tergen'' doesn’t work on my Macbook?

### ISSUE THREAD

**Issue by rubyzn** [CodingEric/Erics-MagicaVoxel-Shaders#3]
I had run other shaders successfully on my Macbook except "tergen", Can't it been run on macOS ?

**Comment by tyanyuy3125** [comment]
Hey there. Don't know if you have got this solved. If not, it's worth noticing that the issue #2 does provided a few approaches to obtain debugging information - which you could paste to here to assist me locate the problem - on MacOS. Hope it can help.
