### ISSUE TITLE
请问在win64位系统下应如何正确使用命令

### ISSUE THREAD

**Issue by Aeant** [CodingEric/Erics-MagicaVoxel-Shaders#4]
这两个着色器，我分别在magicavoxel 0.99.42   0.98.2   0.99.6，在命令行输入用例代码都没有任何效果，能否告知如何正确使用，感激不尽；

project (3d object to 2d plane)
lifegame (A 2d cellular automaton)

**Comment by tyanyuy3125** [comment]
希望您能提供调试信息。issue #2 提供了利用GLIntercept进行的调试信息获取方法。

另外，值得注意的是，“投影”和“生命游戏”两个shader要求场景中有初始体素才能呈现出效果。

因为学业上的事情，就算获得了bug的详细信息，我可能也不能及时予以修正，见谅。

另外感谢您的反馈。

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

发件人: Aeant-黄先森<mailto:notifications@github.com>
发送时间: 2020年12月27日 0:02
收件人: CodingEric/Erics-MagicaVoxel-Shaders<mailto:Erics-MagicaVoxel-Shaders@noreply.github.com>
抄送: Subscribed<mailto:subscribed@noreply.github.com>
主题: [CodingEric/Erics-MagicaVoxel-Shaders] 请问在win64位系统下应如何正确使用命令 (#4)


这两个着色器，我分别在magicavoxel 0.99.42 0.98.2 0.99.6，在命令行输入用例代码都没有任何效果，能否告知如何正确使用，感激不尽；

project (3d object to 2d plane)
lifegame (A 2d cellular automaton)

―

**Comment by Aeant** [comment]
感谢您的回信，按照您说的GLIntercept我尝试过，也没能得到相关日志，可能自我能力问题；
再次感谢，谢谢




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "CodingEric/Erics-MagicaVoxel-Shaders"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年12月27日(星期天) 下午4:01
收件人:&nbsp;"CodingEric/Erics-MagicaVoxel-Shaders"<Erics-MagicaVoxel-Shaders@noreply.github.com&gt;;
抄送:&nbsp;"be 黄先森"<270044376@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [CodingEric/Erics-MagicaVoxel-Shaders] 请问在win64位系统下应如何正确使用命令 (#4)





 希望您能提供调试信息。issue #2 提供了利用GLIntercept进行的调试信息获取方法。 
 
 另外，值得注意的是，“投影”和“生命游戏”两个shader要求场景中有初始体素才能呈现出效果。 
 
 因为学业上的事情，就算获得了bug的详细信息，我可能也不能及时予以修正，见谅。 
 
 另外感谢您的反馈。 
 
 发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986&gt;应用 
 
 发件人: Aeant-黄先森<mailto:notifications@github.com&gt; 
 发送时间: 2020年12月27日 0:02 
 收件人: CodingEric/Erics-MagicaVoxel-Shaders<mailto:Erics-MagicaVoxel-Shaders@noreply.github.com&gt; 
 抄送: Subscribed<mailto:subscribed@noreply.github.com&gt; 
 主题: [CodingEric/Erics-MagicaVoxel-Shaders] 请问在win64位系统下应如何正确使用命令 (#4) 
 
 
 这两个着色器，我分别在magicavoxel 0.99.42 0.98.2 0.99.6，在命令行输入用例代码都没有任何效果，能否告知如何正确使用，感激不尽； 
 
 project (3d object to 2d plane) 
 lifegame (A 2d cellular automaton) 
 
 ―
